version: '3'
services:
  # 1. Database MySQL
  db:
    image: mysql:8.0
    container_name: superstore_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superstore
      MYSQL_USER: analyst
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Metabase (Tools Visualisasi Pengganti Excel)
  metabase:
    image: metabase/metabase
    container_name: superstore_bi
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db
    depends_on:
      - db

volumes:
  db_data: